version: '2'

services:
    nginx:
        image: frey/nginx-reverse-proxy
        ports:
            - 8081:8081
        restart: always

    java-sd:
        depends_on:
          - nginx
        ports:
            - 8080:8080
        image: frey/java-sd
        restart: always 